#!/usr/bin/env python2.7
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright Met Office. All rights reserved.
 For further details please refer to the file COPYRIGHT.txt
 which you should have received as part of this distribution.
*****************************COPYRIGHT******************************
Created on 13 January 2016

@author: Stephen Haddad
'''
import os
import subprocess

import CrayXc40Common

DIR_DICT, SCRIPT_ENV = CrayXc40Common.setup_path_to_scripts()

import XiosModuleWriter
import XiosTestSystem
import unit_test_common

def main():
    """
    Main function for running XIOS test manual script.
    """
    env_vars = SCRIPT_ENV.copy()
    system_name = XiosTestSystem.XiosCrayXC40TestSystem.SYSTEM_NAME
    settings_dict = unit_test_common.get_settings(['oasis3-mct',
                                                   'XIOS',
                                                   'XIOS-app'],
                                                  DIR_DICT['settings'],
                                                  system_name)
    env_vars.update(settings_dict)

    exec_name1 = 'xios_test'
    cmd1 = '''
module use $MODULE_INSTALL_PATH/modules
module load {XIOS_PRGENV}/{XIOS_PRGENV_VERSION}/{ROSE_SUITE_REV_NO}
{EXEC}'''
    cmd1 = cmd1.format(
        EXEC=exec_name1,
        XIOS_PRGENV=XiosModuleWriter.XiosPrgEnvWriter.XIOS_PRGENV_NAME,
        **settings_dict)
    subprocess.call(cmd1,
                    env=env_vars,
                    shell=True)

if __name__ == '__main__':
    main()
