#!/usr/bin/env python2.7
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright Met Office. All rights reserved.
 For further details please refer to the file COPYRIGHT.txt
 which you should have received as part of this distribution.
*****************************COPYRIGHT******************************

Created on 13 January 2016

@author: Stephen Haddad
'''
import os
import subprocess

import CrayXc40Common

DIR_DICT, SCRIPT_ENV = CrayXc40Common.setup_path_to_scripts()

import unit_test_common
import OasisTestSystem

def main():
    """
    Main function for running oasis test manual script.
    """
    env_vars = SCRIPT_ENV.copy()
    system_name = OasisTestSystem.OasisCrayTestSystem.SYSTEM_NAME
    settings_dict = unit_test_common.get_settings(['oasis3-mct','oasis3-mct-test'],
                                                  DIR_DICT['settings'],
                                                  system_name)
    env_vars.update(settings_dict)

    exec_name1 = 'oasis_test'
    cmd1 = ''
    if settings_dict['XBS_SPECIFY_COMPILER_PRGENV'] == 'true':
        compiler_module = settings_dict['XBS_COMPILER_PRGENV']
        cmd1 += 'module swap PrgEnv-cray {0}\n'.format(compiler_module)
    
    prereq_str = ''.join([s1 for s1 in settings_dict['XBS_PREREQ_MODULES']
                          if "'[] ".count(s1) == 0])
    prereq_mod_list = prereq_str.split(',')
    for module_path in prereq_mod_list:
        cmd1 += 'module load {0}\n'.format(module_path)
    cmd1 += '''
module use $MODULE_INSTALL_PATH/modules
module load $OASIS3_MCT/$OASIS_MODULE_VERSION/$ROSE_SUITE_REV_NO/$OASIS_REV_NO
{EXEC}'''
    cmd1 = cmd1.format(EXEC=exec_name1)
    subprocess.call(cmd1,
                    env=env_vars,
                    shell=True)

if __name__ == '__main__':
    main()
