#!/usr/bin/env python
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright Met Office. All rights reserved.
 For further details please refer to the file COPYRIGHT.txt
 which you should have received as part of this distribution.
*****************************COPYRIGHT******************************
Created on 13 January 2016

@author: Stephen Haddad
'''

import os
import subprocess

import CrayXc40Common

DIR_DICT, SCRIPT_ENV = CrayXc40Common.setup_path_to_scripts()

import unit_test_common
import OasisBuildSystem

def main():
    """
    Main function for running oasis build manual script.
    """
    env_vars = SCRIPT_ENV.copy()
    system_name = OasisBuildSystem.OasisCrayBuildSystem.SYSTEM_NAME
    settings_dict = unit_test_common.get_settings(['oasis3-mct'],
                                                  DIR_DICT['settings'],
                                                  system_name)
    env_vars.update(settings_dict)

    exec_name1 = 'oasis_build'

    cmd1 = ''
    if settings_dict['XBS_SPECIFY_COMPILER_PRGENV'] == 'true':
        compiler_module = settings_dict['XBS_COMPILER_PRGENV']
        cmd1 += 'module swap PrgEnv-cray {0}\n'.format(compiler_module)
    for module_path in settings_dict['XBS_PREREQ_MODULES'].split(','):
        cmd1 += 'module load {0}\n'.format(module_path)
    cmd1 += '''
{EXEC}
'''.format(EXEC=exec_name1)

    #print 'running command {0}'.format(cmd1)
    subprocess.call(cmd1,
                    env=env_vars,
                    shell=True)

if __name__ == '__main__':
    main()
