#!/usr/bin/env python2.7
"""
Script to launch GC3.1 test suite using cron job.
"""

import os
import sys
import subprocess
import datetime
import shutil

def main():
    """
    Main function for launching nightly test suite.
    """
    test_dir = os.environ['TESTDIR']
    suite_url = os.environ['SUITE_URL']
    suite_rev = os.environ['SUITE_REV']
    suite_name = os.environ['SUITE_NAME']
    suite_local_dir = os.path.join(test_dir, suite_name)
    header_msg = os.environ['HEADER_MSG']
    add_opts = os.environ['ADD_OPTS']
    msg1 = '{msg} test suite script {datetime}'
    msg1 = msg1.format(msg=header_msg,
                       datetime=str(datetime.datetime.now()))
    print msg1
    sys.stdout.flush()

    # remove anything that exists at this location
    if os.path.exists(suite_local_dir):
        print 'removing existing item at {0}'.format(suite_local_dir)
        sys.stdout.flush()
        if os.path.isdir(suite_local_dir):
            shutil.rmtree(suite_local_dir)
        else:
            os.remove(suite_local_dir)

    #checkout the suite
    checkout_cmd = 'fcm co {url}@{rev} {ldir} -q'
    checkout_cmd = checkout_cmd.format(url=suite_url,
                                       rev=suite_rev,
                                       ldir=suite_local_dir)
    print 'Extracting moci test suite with cmd: {0}'.format(checkout_cmd)
    sys.stdout.flush()
    subprocess.call(checkout_cmd,
                    shell=True)

    os.chdir(suite_local_dir)

    suite_run_cmd = 'rose suite-run --name={0} --new  --no-gcontrol'
    suite_run_cmd += add_opts
    suite_run_cmd = suite_run_cmd.format(suite_name)
    
    print 'Launching moci test suite'
    print 'command: {0}'.format(suite_run_cmd)
    sys.stdout.flush()
    subprocess.call(suite_run_cmd, shell=True)

if __name__ == '__main__':
    main()
