#!/usr/bin/env python2.7
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright 2015-2017 Met Office. All rights reserved.

 Use, duplication or disclosure of this code is subject to the restrictions
 as set forth in the licence. If no licence has been raised with this copy
 of the code, the use, duplication or disclosure of it is strictly
 prohibited. Permission to do so must first be obtained in writing from the
 Met Office Information Asset Owner at the following address:

 Met Office, FitzRoy Road, Exeter, Devon, EX1 3PB, United Kingdom
*****************************COPYRIGHT******************************
'''
import argparse
import unittest
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir))
sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'common'))
sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'atmos'))
sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir, 'nemocice'))
sys.path.append(os.path.join(os.path.dirname(__file__), os.pardir,
                             'archive_verify'))

# Setup a null timer instance to ensure the decorated functions behave
# correctly with the unit tests
import runtime_environment
runtime_environment.setup_env()
import timer
timer.set_nulltimer()


def main():
    '''Run unit tests for postproc app'''
    groups = {
        'all':      'test_*.py',
        'main':     'test_main.py',
        'common':   'test_common_*.py',
        'control':  'test_common_control.py',
        'suitegen': 'test_common_suitegen.py',
        'nlist':    'test_common_nlist.py',
        'utils':    'test_common_utils.py',
        'timer':    'test_common_timer.py',
        'moo':      'test_common_moo.py',
        'netcdf':   'test_common_netcdf_*.py',
        'iris':     'test_common_iris.py',
        'atmos':    'test_atmos_*.py',
        'atmbase':  'test_atmos_base.py',
        'atmutils': 'test_atmos_utils.py',
        'nemocice': 'test_nemocice*.py',
        'nemo':     'test_nemocice_nemo.py',
        'cice':     'test_nemocice_cice.py',
        'template': 'test_nemocice_template.py',
        'verify':   'test_verify_*.py',
        }

    subgroups = [
        ' '.join(['common groups:'] + [c for c in groups.keys() if
                                       'common_' in groups[c]]),
        ' '.join(['atmos groups:'] + [a for a in groups.keys() if
                                      'atmos_' in groups[a]]),
        ' '.join(['nemo and cice groups:'] + [n for n in groups.keys() if
                                              'nemocice_' in groups[n]]),
        ' '.join(['verification group:'] + [v for v in groups.keys() if
                                            'verify_' in groups[v]]),
        ]

    parser = argparse.ArgumentParser(
        description='MOCI PostProcessing App UnitTests',
        formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('-g', '--group',
                        help='''Specify a group of tests to run.  Default=all
Additional groups may be requested with further --group arguments.
Available groups: \n\t{}'''.format('\n\t'.join(subgroups)),
                        action='append')
    args = parser.parse_args()

    if args.group:
        testgroup = args.group
    else:
        testgroup = ['all']

    rtn_code = 0
    for grp in testgroup:
        try:
            test_suite = unittest.TestLoader().\
                discover(os.path.dirname(os.path.realpath(__file__)),
                         pattern=groups[grp])
        except KeyError:
            print '[ERROR] UnitTest - Unknown group: {}.  See help'.format(grp)
            continue
        print '[INFO] Running test group: {}'.format(grp)
        test_rtn = unittest.TextTestRunner(buffer=True).run(test_suite)
        rtn_code += len(test_rtn.failures) + len(test_rtn.errors)

    exit(rtn_code)

if __name__ == '__main__':
    main()
