#!/usr/bin/env python3
"""
#*****************************COPYRIGHT******************************
(C) Crown copyright 2018-2025 Met Office. All rights reserved.

 Use, duplication or disclosure of this code is subject to the restrictions
 as set forth in the licence. If no licence has been raised with this copy
 of the code, the use, duplication or disclosure of it is strictly
 prohibited. Permission to do so must first be obtained in writing from the
 Met Office Information Asset Owner at the following address:

 Met Office, FitzRoy Road, Exeter, Devon, EX1 3PB, United Kingdom
#*****************************COPYRIGHT******************************
 NAME
   compare_nemo_solver_output

 USAGE
   Compare 2 NEMO solver.stat or run.stat (NEMO4.0) files

"""

import argparse

import test_common
import compare_nemo_solver_stat

HELP_INPUT1 = 'Path to the first solver.stat or run.stat input file'
HELP_INPUT2 = 'Path to the second solver.stat or run.stat input file'

def get_command_line_arguments():
    """
    Get command line arguments
    """
    desc_msg = ''
    parser = argparse.ArgumentParser(description=desc_msg)
    parser.add_argument('--input1',
                        dest='input1',
                        help=HELP_INPUT1)
    parser.add_argument('--input2',
                        dest='input2',
                        help=HELP_INPUT2)
    parser.add_argument('--list-errors',
                        dest='list_errors',
                        action='store_true',
                        help=test_common.HELP_LIST_ERRORS)
    parser.add_argument('--timestep-num-offset',
                        dest='timestep_num_offset',
                        help=test_common.HELP_SOLVER_OFFSET,
                        type=int,
                        default=0)

    cmd_args = parser.parse_args()
    return (cmd_args.input1,
            cmd_args.input2,
            cmd_args.list_errors,
            cmd_args.timestep_num_offset)


def main():
    """
    Main function for comparing NEMO solver.stat or run.stat files.
    """
    path1, path2, list_errors, timestep_num_offset = \
        get_command_line_arguments()
    io_manager = test_common.TestIO()
    exit_code = \
        compare_nemo_solver_stat.compare_solver_stat_files(
            path1,
            path2,
            list_errors,
            False,
            timestep_num_offset,
            io_manager)
    exit(exit_code)

if __name__ == '__main__':
    main()
