#!/usr/bin/env python2.7
'''
Created on 18 Novemeber 2015

@author: Stephen Haddad

Creates directories to store data generated by rose stem tests. The data
is generated on the remote platform and then copied back to the launch 
platform to the directories created here where it is checked for errors.
'''
import os
import shutil

def main():
    xios_result_dir = os.environ['XIOS_RESULT_DIR']
    if os.path.exists(xios_result_dir) and \
        os.path.isdir(xios_result_dir):
        shutil.rmtree(xios_result_dir)
    os.makedirs(xios_result_dir)
        
        
    oasis_result_dir = os.environ['OASIS_RESULT_DIR']
    if os.path.exists(oasis_result_dir) and \
        os.path.isdir(oasis_result_dir):
        shutil.rmtree(oasis_result_dir)
    os.makedirs(oasis_result_dir)

    nemo_result_dir = os.environ['NEMO_RESULT_DIR']
    if os.path.exists(nemo_result_dir) and \
        os.path.isdir(nemo_result_dir):
        shutil.rmtree(nemo_result_dir)
    os.makedirs(nemo_result_dir)

if __name__ == '__main__':
    main()