#!/usr/bin/env bash
#*****************************COPYRIGHT******************************
# (C) Crown copyright 2021 Met Office. All rights reserved.
#
# Use, duplication or disclosure of this code is subject to the restrictions
# as set forth in the licence. If no licence has been raised with this copy
# of the code, the use, duplication or disclosure of it is strictly
# prohibited. Permission to do so must first be obtained in writing from the
# Met Office Information Asset Owner at the following address:
#
# Met Office, FitzRoy Road, Exeter, Devon, EX1 3PB, United Kingdom
#*****************************COPYRIGHT******************************
# NAME
#     run_model
#
# DESCRIPTION
#     Run the drivers (via link_drivers), export the environment variables
#     as required (via driver_envar), run the model (via driver_cmd) and
#     finalize the model using the drivers (via link_drivers --finalize)

# Fail if environment variables are unset, for sanitys sake
set -eu

echo $CYLC_SUITE_RUN_DIR

# Set a default value for the driver extract directory to allow for backward
# compatibility, and future flexibility
DRIVER_EXTRACT_DIR=${DRIVER_EXTRACT_DIR:=$CYLC_SUITE_SHARE_DIR/fcm_make_drivers}

echo "[DRIVER_TEST_SCRIPT] DRIVER_EXTRACT_DIR is $DRIVER_EXTRACT_DIR" 

# This lets us set up a failure mode
export DRIVERS_FINALISED=false

# Are we using the mct_validate utility to check on the coupled model setup
# Must be set to true to run validation
L_MCT_VALIDATE=${L_MCT_VALIDATE:=false}


# Copy scripts to work directory so they can be found.
cp $DRIVER_EXTRACT_DIR/build/bin/* ./

# Copy our packages to work directory so they can be found
cp -r $DRIVER_EXTRACT_DIR/extract/drivers/Coupled_Drivers/dr_*_lib ./

# Run our drivers, this produces two command files
#  driver_envar containing environment variables to be exported
#  driver_cmd containing a command for the system launcher
./link_drivers --run

echo '[DRIVER_TEST_SCRIPT] Drivers successfully linked'

# Validate mct setup if required. This must be done after the link stage to
# ensure that any dynamic namcouple setup, namelist setup, and file moving
# had been completed
if [ "$L_MCT_VALIDATE" = True ]; then
    ./mct_validate.py
fi

# Process after any failures
SIGNALS='EXIT'
FINALLY() {
    echo "Finally!"
    for S in $SIGNALS; do
        trap '' $S #switch off traps
    done
    if [ "$DRIVERS_FINALISED" = true ]; then
        echo "Completed successfully"
    else
        echo 'Trying to run driver in failure mode'
        ./link_drivers --failure
    fi
}

for S in $SIGNALS; do
    trap 'FINALLY' $S
done

# Export the enviromnent variables from all the drivers
source driver_envar
# Run the aprun command and provide timing information if required
start=$(date +%s)
source driver_cmd
end=$(date +%s)

time_in_aprun=$((end-start))
echo "[DRIVER_TEST_SCRIPT] $time_in_aprun seconds are spent in APRUN"

#export time_in_aprun variable so the cpmip controller can find it if required
export time_in_aprun

# Run the drivers in finalize mode (after completion of the model). This deals
# with model standard out / standard error, and also with any file details
# required prior to the start of the next model cycle (if applicable). If
# aprun has failed, we run the drivers in a stripped down failure mode
echo '[DRIVER_TEST_SCRIPT] Finalizing drivers'
./link_drivers --finalize;
export DRIVERS_FINALISED=true
