#!/usr/bin/env python
"""
Script to run all test on the Linux desktop platoform with Intel compiler

WARNING! These tests are broken. The Linux/Intel platform version of these
build/test scripts is not currently working but should be fixed soon.
"""
import unittest
import sys
import os
import datetime

SCRIPT_DIR = os.path.abspath(os.path.join(os.path.realpath(__file__),
                                          os.pardir,
                                          os.pardir))
sys.path += [SCRIPT_DIR]

LIB_DIR = os.path.abspath(os.path.join(SCRIPT_DIR,
                                       'lib'))
sys.path += [LIB_DIR]

from xios_build_tests import XiosBuildLinuxIntelTests
from nemo_build_tests import NemoBuildLinuxIntelTests


SCRATCH_DIR_NAME = 'scratch_XBStest_'

def main():
    """
    Main function
    """
    # setting up working directory. A directory can be passed in as argument
    # or the current directory will be used. The actual files will be put in
    # a subdirectory of the current or input directory
    if len(sys.argv) < 2:
        working_dir = os.getcwd()
    else:
        working_dir = sys.argv[1]
    date_time_str = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')
    working_dir = os.path.join(working_dir,
                               SCRATCH_DIR_NAME + '_' + date_time_str)
    if not (os.path.exists(working_dir) and os.path.isdir(working_dir)):
        os.mkdir(working_dir)
    os.chdir(working_dir)
    msg1 = 'test files will be created in {testDir}'
    print(msg1.format(testDir=os.getcwd()))

    module_suites = [
        unittest.TestLoader().loadTestsFromTestCase(XiosBuildLinuxIntelTests),
        unittest.TestLoader().loadTestsFromTestCase(NemoBuildLinuxIntelTests)]
    linux_suite = unittest.TestSuite(module_suites)

    unittest.TextTestRunner(verbosity=2).run(linux_suite)

if __name__ == '__main__':
    main()
