#!/usr/bin/env python2.7

import unittest
import sys
import os
import datetime

# find parent directory directory containing this file so that source code 
# can be imported 
SCRIPT_DIR = os.path.abspath(os.path.join(os.path.realpath(__file__),
                                          os.pardir,
                                          os.pardir))
sys.path += [SCRIPT_DIR]
from xiosBuildTests import XiosBuildCrayTests
from nemoBuildTests import NemoBuildCrayTests
from oasisBuildTests import OasisBuildCrayTests

SCRATCH_DIR_NAME='scratch_XBStest_'

def main():
    # setting up working directory. A directory can be passed in as argument
    # or the current directory will be used. The actual files will be put in
    # a subdirectory of the current or input directory 
    if len(sys.argv) <2:
        workingDir = os.getcwd()
    else:
        workingDir = sys.argv[1]
    dateTimeStr = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')
    workingDir = os.path.join(workingDir,
                              SCRATCH_DIR_NAME + '_' + dateTimeStr)
    if not (os.path.exists(workingDir) and os.path.isdir(workingDir)):
        os.mkdir(workingDir)
    os.chdir(workingDir)
    print 'test files will be created in {testDir}'.format(testDir=os.getcwd())

    moduleSuites = []
    moduleSuites += [unittest.TestLoader().loadTestsFromTestCase(XiosBuildCrayTests)]
    moduleSuites += [unittest.TestLoader().loadTestsFromTestCase(NemoBuildCrayTests)]
    moduleSuites += [unittest.TestLoader().loadTestsFromTestCase(OasisBuildCrayTests)]
    craySuite = unittest.TestSuite(moduleSuites)
    
    testResults = unittest.TextTestRunner(verbosity=2).run(craySuite)
    if len(testResults.errors) > 0 or len(testResults.failures) > 0:
        exit(1)
       

if __name__ == '__main__':
    main()  